# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\Program_Professional\CMake\bin\cmake.exe

# The command to remove a file.
RM = D:\Program_Professional\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = K:\Project_WXP\20241131_FEM_Palace\FEM_GPU\gslib_windows

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = K:\Project_WXP\20241131_FEM_Palace\FEM_GPU\gslib_windows

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:\Program_Professional\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:\Program_Professional\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components\fast: list_install_components
.PHONY : list_install_components\fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	D:\Program_Professional\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	D:\Program_Professional\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install\fast

# Special rule for the target install/local
install\local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	D:\Program_Professional\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local

# Special rule for the target install/local
install\local\fast: preinstall\fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	D:\Program_Professional\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install\local\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start K:\Project_WXP\20241131_FEM_Palace\FEM_GPU\gslib_windows\CMakeFiles K:\Project_WXP\20241131_FEM_Palace\FEM_GPU\gslib_windows\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start K:\Project_WXP\20241131_FEM_Palace\FEM_GPU\gslib_windows\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gs

# Build rule for target.
gs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gs
.PHONY : gs

# fast build rule for target.
gs\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\build
.PHONY : gs\fast

#=============================================================================
# Target rules for targets named sort_test

# Build rule for target.
sort_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) sort_test
.PHONY : sort_test

# fast build rule for target.
sort_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test.dir\build
.PHONY : sort_test\fast

#=============================================================================
# Target rules for targets named sort_test2

# Build rule for target.
sort_test2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) sort_test2
.PHONY : sort_test2

# fast build rule for target.
sort_test2\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test2.dir\build
.PHONY : sort_test2\fast

#=============================================================================
# Target rules for targets named sarray_sort_test

# Build rule for target.
sarray_sort_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) sarray_sort_test
.PHONY : sarray_sort_test

# fast build rule for target.
sarray_sort_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_sort_test.dir\build
.PHONY : sarray_sort_test\fast

#=============================================================================
# Target rules for targets named comm_test

# Build rule for target.
comm_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) comm_test
.PHONY : comm_test

# fast build rule for target.
comm_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\comm_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\comm_test.dir\build
.PHONY : comm_test\fast

#=============================================================================
# Target rules for targets named crystal_test

# Build rule for target.
crystal_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) crystal_test
.PHONY : crystal_test

# fast build rule for target.
crystal_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\crystal_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\crystal_test.dir\build
.PHONY : crystal_test\fast

#=============================================================================
# Target rules for targets named sarray_transfer_test

# Build rule for target.
sarray_transfer_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) sarray_transfer_test
.PHONY : sarray_transfer_test

# fast build rule for target.
sarray_transfer_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_transfer_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_transfer_test.dir\build
.PHONY : sarray_transfer_test\fast

#=============================================================================
# Target rules for targets named gs_test

# Build rule for target.
gs_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gs_test
.PHONY : gs_test

# fast build rule for target.
gs_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test.dir\build
.PHONY : gs_test\fast

#=============================================================================
# Target rules for targets named gs_test_gop_blocking

# Build rule for target.
gs_test_gop_blocking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gs_test_gop_blocking
.PHONY : gs_test_gop_blocking

# fast build rule for target.
gs_test_gop_blocking\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_blocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_blocking.dir\build
.PHONY : gs_test_gop_blocking\fast

#=============================================================================
# Target rules for targets named gs_test_gop_nonblocking

# Build rule for target.
gs_test_gop_nonblocking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gs_test_gop_nonblocking
.PHONY : gs_test_gop_nonblocking

# fast build rule for target.
gs_test_gop_nonblocking\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_nonblocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_nonblocking.dir\build
.PHONY : gs_test_gop_nonblocking\fast

#=============================================================================
# Target rules for targets named gs_unique_test

# Build rule for target.
gs_unique_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) gs_unique_test
.PHONY : gs_unique_test

# fast build rule for target.
gs_unique_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_unique_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_unique_test.dir\build
.PHONY : gs_unique_test\fast

#=============================================================================
# Target rules for targets named findpts_el_2_test

# Build rule for target.
findpts_el_2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_el_2_test
.PHONY : findpts_el_2_test

# fast build rule for target.
findpts_el_2_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test.dir\build
.PHONY : findpts_el_2_test\fast

#=============================================================================
# Target rules for targets named findpts_el_2_test2

# Build rule for target.
findpts_el_2_test2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_el_2_test2
.PHONY : findpts_el_2_test2

# fast build rule for target.
findpts_el_2_test2\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test2.dir\build
.PHONY : findpts_el_2_test2\fast

#=============================================================================
# Target rules for targets named findpts_el_3_test

# Build rule for target.
findpts_el_3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_el_3_test
.PHONY : findpts_el_3_test

# fast build rule for target.
findpts_el_3_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test.dir\build
.PHONY : findpts_el_3_test\fast

#=============================================================================
# Target rules for targets named findpts_el_3_test2

# Build rule for target.
findpts_el_3_test2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_el_3_test2
.PHONY : findpts_el_3_test2

# fast build rule for target.
findpts_el_3_test2\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test2.dir\build
.PHONY : findpts_el_3_test2\fast

#=============================================================================
# Target rules for targets named findpts_local_test

# Build rule for target.
findpts_local_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_local_test
.PHONY : findpts_local_test

# fast build rule for target.
findpts_local_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_local_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_local_test.dir\build
.PHONY : findpts_local_test\fast

#=============================================================================
# Target rules for targets named findpts_test

# Build rule for target.
findpts_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_test
.PHONY : findpts_test

# fast build rule for target.
findpts_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test.dir\build
.PHONY : findpts_test\fast

#=============================================================================
# Target rules for targets named findpts_test_ms

# Build rule for target.
findpts_test_ms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) findpts_test_ms
.PHONY : findpts_test_ms

# fast build rule for target.
findpts_test_ms\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test_ms.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test_ms.dir\build
.PHONY : findpts_test_ms\fast

#=============================================================================
# Target rules for targets named poly_test

# Build rule for target.
poly_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) poly_test
.PHONY : poly_test

# fast build rule for target.
poly_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\poly_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\poly_test.dir\build
.PHONY : poly_test\fast

#=============================================================================
# Target rules for targets named lob_bnd_test

# Build rule for target.
lob_bnd_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) lob_bnd_test
.PHONY : lob_bnd_test

# fast build rule for target.
lob_bnd_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lob_bnd_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\lob_bnd_test.dir\build
.PHONY : lob_bnd_test\fast

#=============================================================================
# Target rules for targets named obbox_test

# Build rule for target.
obbox_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) obbox_test
.PHONY : obbox_test

# fast build rule for target.
obbox_test\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\obbox_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\obbox_test.dir\build
.PHONY : obbox_test\fast

src\comm.obj: src\comm.c.obj
.PHONY : src\comm.obj

# target to build an object file
src\comm.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\comm.c.obj
.PHONY : src\comm.c.obj

src\comm.i: src\comm.c.i
.PHONY : src\comm.i

# target to preprocess a source file
src\comm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\comm.c.i
.PHONY : src\comm.c.i

src\comm.s: src\comm.c.s
.PHONY : src\comm.s

# target to generate assembly for a file
src\comm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\comm.c.s
.PHONY : src\comm.c.s

src\crystal.obj: src\crystal.c.obj
.PHONY : src\crystal.obj

# target to build an object file
src\crystal.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\crystal.c.obj
.PHONY : src\crystal.c.obj

src\crystal.i: src\crystal.c.i
.PHONY : src\crystal.i

# target to preprocess a source file
src\crystal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\crystal.c.i
.PHONY : src\crystal.c.i

src\crystal.s: src\crystal.c.s
.PHONY : src\crystal.s

# target to generate assembly for a file
src\crystal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\crystal.c.s
.PHONY : src\crystal.c.s

src\fail.obj: src\fail.c.obj
.PHONY : src\fail.obj

# target to build an object file
src\fail.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fail.c.obj
.PHONY : src\fail.c.obj

src\fail.i: src\fail.c.i
.PHONY : src\fail.i

# target to preprocess a source file
src\fail.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fail.c.i
.PHONY : src\fail.c.i

src\fail.s: src\fail.c.s
.PHONY : src\fail.s

# target to generate assembly for a file
src\fail.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fail.c.s
.PHONY : src\fail.c.s

src\fcrystal.obj: src\fcrystal.c.obj
.PHONY : src\fcrystal.obj

# target to build an object file
src\fcrystal.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fcrystal.c.obj
.PHONY : src\fcrystal.c.obj

src\fcrystal.i: src\fcrystal.c.i
.PHONY : src\fcrystal.i

# target to preprocess a source file
src\fcrystal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fcrystal.c.i
.PHONY : src\fcrystal.c.i

src\fcrystal.s: src\fcrystal.c.s
.PHONY : src\fcrystal.s

# target to generate assembly for a file
src\fcrystal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\fcrystal.c.s
.PHONY : src\fcrystal.c.s

src\findpts.obj: src\findpts.c.obj
.PHONY : src\findpts.obj

# target to build an object file
src\findpts.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts.c.obj
.PHONY : src\findpts.c.obj

src\findpts.i: src\findpts.c.i
.PHONY : src\findpts.i

# target to preprocess a source file
src\findpts.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts.c.i
.PHONY : src\findpts.c.i

src\findpts.s: src\findpts.c.s
.PHONY : src\findpts.s

# target to generate assembly for a file
src\findpts.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts.c.s
.PHONY : src\findpts.c.s

src\findpts_el_2.obj: src\findpts_el_2.c.obj
.PHONY : src\findpts_el_2.obj

# target to build an object file
src\findpts_el_2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_2.c.obj
.PHONY : src\findpts_el_2.c.obj

src\findpts_el_2.i: src\findpts_el_2.c.i
.PHONY : src\findpts_el_2.i

# target to preprocess a source file
src\findpts_el_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_2.c.i
.PHONY : src\findpts_el_2.c.i

src\findpts_el_2.s: src\findpts_el_2.c.s
.PHONY : src\findpts_el_2.s

# target to generate assembly for a file
src\findpts_el_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_2.c.s
.PHONY : src\findpts_el_2.c.s

src\findpts_el_3.obj: src\findpts_el_3.c.obj
.PHONY : src\findpts_el_3.obj

# target to build an object file
src\findpts_el_3.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_3.c.obj
.PHONY : src\findpts_el_3.c.obj

src\findpts_el_3.i: src\findpts_el_3.c.i
.PHONY : src\findpts_el_3.i

# target to preprocess a source file
src\findpts_el_3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_3.c.i
.PHONY : src\findpts_el_3.c.i

src\findpts_el_3.s: src\findpts_el_3.c.s
.PHONY : src\findpts_el_3.s

# target to generate assembly for a file
src\findpts_el_3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_el_3.c.s
.PHONY : src\findpts_el_3.c.s

src\findpts_local.obj: src\findpts_local.c.obj
.PHONY : src\findpts_local.obj

# target to build an object file
src\findpts_local.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_local.c.obj
.PHONY : src\findpts_local.c.obj

src\findpts_local.i: src\findpts_local.c.i
.PHONY : src\findpts_local.i

# target to preprocess a source file
src\findpts_local.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_local.c.i
.PHONY : src\findpts_local.c.i

src\findpts_local.s: src\findpts_local.c.s
.PHONY : src\findpts_local.s

# target to generate assembly for a file
src\findpts_local.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\findpts_local.c.s
.PHONY : src\findpts_local.c.s

src\gs.obj: src\gs.c.obj
.PHONY : src\gs.obj

# target to build an object file
src\gs.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs.c.obj
.PHONY : src\gs.c.obj

src\gs.i: src\gs.c.i
.PHONY : src\gs.i

# target to preprocess a source file
src\gs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs.c.i
.PHONY : src\gs.c.i

src\gs.s: src\gs.c.s
.PHONY : src\gs.s

# target to generate assembly for a file
src\gs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs.c.s
.PHONY : src\gs.c.s

src\gs_local.obj: src\gs_local.c.obj
.PHONY : src\gs_local.obj

# target to build an object file
src\gs_local.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs_local.c.obj
.PHONY : src\gs_local.c.obj

src\gs_local.i: src\gs_local.c.i
.PHONY : src\gs_local.i

# target to preprocess a source file
src\gs_local.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs_local.c.i
.PHONY : src\gs_local.c.i

src\gs_local.s: src\gs_local.c.s
.PHONY : src\gs_local.s

# target to generate assembly for a file
src\gs_local.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\gs_local.c.s
.PHONY : src\gs_local.c.s

src\lob_bnd.obj: src\lob_bnd.c.obj
.PHONY : src\lob_bnd.obj

# target to build an object file
src\lob_bnd.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\lob_bnd.c.obj
.PHONY : src\lob_bnd.c.obj

src\lob_bnd.i: src\lob_bnd.c.i
.PHONY : src\lob_bnd.i

# target to preprocess a source file
src\lob_bnd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\lob_bnd.c.i
.PHONY : src\lob_bnd.c.i

src\lob_bnd.s: src\lob_bnd.c.s
.PHONY : src\lob_bnd.s

# target to generate assembly for a file
src\lob_bnd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\lob_bnd.c.s
.PHONY : src\lob_bnd.c.s

src\obbox.obj: src\obbox.c.obj
.PHONY : src\obbox.obj

# target to build an object file
src\obbox.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\obbox.c.obj
.PHONY : src\obbox.c.obj

src\obbox.i: src\obbox.c.i
.PHONY : src\obbox.i

# target to preprocess a source file
src\obbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\obbox.c.i
.PHONY : src\obbox.c.i

src\obbox.s: src\obbox.c.s
.PHONY : src\obbox.s

# target to generate assembly for a file
src\obbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\obbox.c.s
.PHONY : src\obbox.c.s

src\poly.obj: src\poly.c.obj
.PHONY : src\poly.obj

# target to build an object file
src\poly.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\poly.c.obj
.PHONY : src\poly.c.obj

src\poly.i: src\poly.c.i
.PHONY : src\poly.i

# target to preprocess a source file
src\poly.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\poly.c.i
.PHONY : src\poly.c.i

src\poly.s: src\poly.c.s
.PHONY : src\poly.s

# target to generate assembly for a file
src\poly.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\poly.c.s
.PHONY : src\poly.c.s

src\sarray_sort.obj: src\sarray_sort.c.obj
.PHONY : src\sarray_sort.obj

# target to build an object file
src\sarray_sort.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_sort.c.obj
.PHONY : src\sarray_sort.c.obj

src\sarray_sort.i: src\sarray_sort.c.i
.PHONY : src\sarray_sort.i

# target to preprocess a source file
src\sarray_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_sort.c.i
.PHONY : src\sarray_sort.c.i

src\sarray_sort.s: src\sarray_sort.c.s
.PHONY : src\sarray_sort.s

# target to generate assembly for a file
src\sarray_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_sort.c.s
.PHONY : src\sarray_sort.c.s

src\sarray_transfer.obj: src\sarray_transfer.c.obj
.PHONY : src\sarray_transfer.obj

# target to build an object file
src\sarray_transfer.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_transfer.c.obj
.PHONY : src\sarray_transfer.c.obj

src\sarray_transfer.i: src\sarray_transfer.c.i
.PHONY : src\sarray_transfer.i

# target to preprocess a source file
src\sarray_transfer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_transfer.c.i
.PHONY : src\sarray_transfer.c.i

src\sarray_transfer.s: src\sarray_transfer.c.s
.PHONY : src\sarray_transfer.s

# target to generate assembly for a file
src\sarray_transfer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sarray_transfer.c.s
.PHONY : src\sarray_transfer.c.s

src\sort.obj: src\sort.c.obj
.PHONY : src\sort.obj

# target to build an object file
src\sort.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sort.c.obj
.PHONY : src\sort.c.obj

src\sort.i: src\sort.c.i
.PHONY : src\sort.i

# target to preprocess a source file
src\sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sort.c.i
.PHONY : src\sort.c.i

src\sort.s: src\sort.c.s
.PHONY : src\sort.s

# target to generate assembly for a file
src\sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\sort.c.s
.PHONY : src\sort.c.s

src\tensor.obj: src\tensor.c.obj
.PHONY : src\tensor.obj

# target to build an object file
src\tensor.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\tensor.c.obj
.PHONY : src\tensor.c.obj

src\tensor.i: src\tensor.c.i
.PHONY : src\tensor.i

# target to preprocess a source file
src\tensor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\tensor.c.i
.PHONY : src\tensor.c.i

src\tensor.s: src\tensor.c.s
.PHONY : src\tensor.s

# target to generate assembly for a file
src\tensor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs.dir\src\tensor.c.s
.PHONY : src\tensor.c.s

tests\comm_test.obj: tests\comm_test.c.obj
.PHONY : tests\comm_test.obj

# target to build an object file
tests\comm_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\comm_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\comm_test.dir\tests\comm_test.c.obj
.PHONY : tests\comm_test.c.obj

tests\comm_test.i: tests\comm_test.c.i
.PHONY : tests\comm_test.i

# target to preprocess a source file
tests\comm_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\comm_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\comm_test.dir\tests\comm_test.c.i
.PHONY : tests\comm_test.c.i

tests\comm_test.s: tests\comm_test.c.s
.PHONY : tests\comm_test.s

# target to generate assembly for a file
tests\comm_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\comm_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\comm_test.dir\tests\comm_test.c.s
.PHONY : tests\comm_test.c.s

tests\crystal_test.obj: tests\crystal_test.c.obj
.PHONY : tests\crystal_test.obj

# target to build an object file
tests\crystal_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\crystal_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\crystal_test.dir\tests\crystal_test.c.obj
.PHONY : tests\crystal_test.c.obj

tests\crystal_test.i: tests\crystal_test.c.i
.PHONY : tests\crystal_test.i

# target to preprocess a source file
tests\crystal_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\crystal_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\crystal_test.dir\tests\crystal_test.c.i
.PHONY : tests\crystal_test.c.i

tests\crystal_test.s: tests\crystal_test.c.s
.PHONY : tests\crystal_test.s

# target to generate assembly for a file
tests\crystal_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\crystal_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\crystal_test.dir\tests\crystal_test.c.s
.PHONY : tests\crystal_test.c.s

tests\findpts_el_2_test.obj: tests\findpts_el_2_test.c.obj
.PHONY : tests\findpts_el_2_test.obj

# target to build an object file
tests\findpts_el_2_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test.dir\tests\findpts_el_2_test.c.obj
.PHONY : tests\findpts_el_2_test.c.obj

tests\findpts_el_2_test.i: tests\findpts_el_2_test.c.i
.PHONY : tests\findpts_el_2_test.i

# target to preprocess a source file
tests\findpts_el_2_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test.dir\tests\findpts_el_2_test.c.i
.PHONY : tests\findpts_el_2_test.c.i

tests\findpts_el_2_test.s: tests\findpts_el_2_test.c.s
.PHONY : tests\findpts_el_2_test.s

# target to generate assembly for a file
tests\findpts_el_2_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test.dir\tests\findpts_el_2_test.c.s
.PHONY : tests\findpts_el_2_test.c.s

tests\findpts_el_2_test2.obj: tests\findpts_el_2_test2.c.obj
.PHONY : tests\findpts_el_2_test2.obj

# target to build an object file
tests\findpts_el_2_test2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test2.dir\tests\findpts_el_2_test2.c.obj
.PHONY : tests\findpts_el_2_test2.c.obj

tests\findpts_el_2_test2.i: tests\findpts_el_2_test2.c.i
.PHONY : tests\findpts_el_2_test2.i

# target to preprocess a source file
tests\findpts_el_2_test2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test2.dir\tests\findpts_el_2_test2.c.i
.PHONY : tests\findpts_el_2_test2.c.i

tests\findpts_el_2_test2.s: tests\findpts_el_2_test2.c.s
.PHONY : tests\findpts_el_2_test2.s

# target to generate assembly for a file
tests\findpts_el_2_test2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_2_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_2_test2.dir\tests\findpts_el_2_test2.c.s
.PHONY : tests\findpts_el_2_test2.c.s

tests\findpts_el_3_test.obj: tests\findpts_el_3_test.c.obj
.PHONY : tests\findpts_el_3_test.obj

# target to build an object file
tests\findpts_el_3_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test.dir\tests\findpts_el_3_test.c.obj
.PHONY : tests\findpts_el_3_test.c.obj

tests\findpts_el_3_test.i: tests\findpts_el_3_test.c.i
.PHONY : tests\findpts_el_3_test.i

# target to preprocess a source file
tests\findpts_el_3_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test.dir\tests\findpts_el_3_test.c.i
.PHONY : tests\findpts_el_3_test.c.i

tests\findpts_el_3_test.s: tests\findpts_el_3_test.c.s
.PHONY : tests\findpts_el_3_test.s

# target to generate assembly for a file
tests\findpts_el_3_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test.dir\tests\findpts_el_3_test.c.s
.PHONY : tests\findpts_el_3_test.c.s

tests\findpts_el_3_test2.obj: tests\findpts_el_3_test2.c.obj
.PHONY : tests\findpts_el_3_test2.obj

# target to build an object file
tests\findpts_el_3_test2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test2.dir\tests\findpts_el_3_test2.c.obj
.PHONY : tests\findpts_el_3_test2.c.obj

tests\findpts_el_3_test2.i: tests\findpts_el_3_test2.c.i
.PHONY : tests\findpts_el_3_test2.i

# target to preprocess a source file
tests\findpts_el_3_test2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test2.dir\tests\findpts_el_3_test2.c.i
.PHONY : tests\findpts_el_3_test2.c.i

tests\findpts_el_3_test2.s: tests\findpts_el_3_test2.c.s
.PHONY : tests\findpts_el_3_test2.s

# target to generate assembly for a file
tests\findpts_el_3_test2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_el_3_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_el_3_test2.dir\tests\findpts_el_3_test2.c.s
.PHONY : tests\findpts_el_3_test2.c.s

tests\findpts_local_test.obj: tests\findpts_local_test.c.obj
.PHONY : tests\findpts_local_test.obj

# target to build an object file
tests\findpts_local_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_local_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_local_test.dir\tests\findpts_local_test.c.obj
.PHONY : tests\findpts_local_test.c.obj

tests\findpts_local_test.i: tests\findpts_local_test.c.i
.PHONY : tests\findpts_local_test.i

# target to preprocess a source file
tests\findpts_local_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_local_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_local_test.dir\tests\findpts_local_test.c.i
.PHONY : tests\findpts_local_test.c.i

tests\findpts_local_test.s: tests\findpts_local_test.c.s
.PHONY : tests\findpts_local_test.s

# target to generate assembly for a file
tests\findpts_local_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_local_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_local_test.dir\tests\findpts_local_test.c.s
.PHONY : tests\findpts_local_test.c.s

tests\findpts_test.obj: tests\findpts_test.c.obj
.PHONY : tests\findpts_test.obj

# target to build an object file
tests\findpts_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test.dir\tests\findpts_test.c.obj
.PHONY : tests\findpts_test.c.obj

tests\findpts_test.i: tests\findpts_test.c.i
.PHONY : tests\findpts_test.i

# target to preprocess a source file
tests\findpts_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test.dir\tests\findpts_test.c.i
.PHONY : tests\findpts_test.c.i

tests\findpts_test.s: tests\findpts_test.c.s
.PHONY : tests\findpts_test.s

# target to generate assembly for a file
tests\findpts_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test.dir\tests\findpts_test.c.s
.PHONY : tests\findpts_test.c.s

tests\findpts_test_ms.obj: tests\findpts_test_ms.c.obj
.PHONY : tests\findpts_test_ms.obj

# target to build an object file
tests\findpts_test_ms.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test_ms.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test_ms.dir\tests\findpts_test_ms.c.obj
.PHONY : tests\findpts_test_ms.c.obj

tests\findpts_test_ms.i: tests\findpts_test_ms.c.i
.PHONY : tests\findpts_test_ms.i

# target to preprocess a source file
tests\findpts_test_ms.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test_ms.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test_ms.dir\tests\findpts_test_ms.c.i
.PHONY : tests\findpts_test_ms.c.i

tests\findpts_test_ms.s: tests\findpts_test_ms.c.s
.PHONY : tests\findpts_test_ms.s

# target to generate assembly for a file
tests\findpts_test_ms.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\findpts_test_ms.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\findpts_test_ms.dir\tests\findpts_test_ms.c.s
.PHONY : tests\findpts_test_ms.c.s

tests\gs_test.obj: tests\gs_test.c.obj
.PHONY : tests\gs_test.obj

# target to build an object file
tests\gs_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test.dir\tests\gs_test.c.obj
.PHONY : tests\gs_test.c.obj

tests\gs_test.i: tests\gs_test.c.i
.PHONY : tests\gs_test.i

# target to preprocess a source file
tests\gs_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test.dir\tests\gs_test.c.i
.PHONY : tests\gs_test.c.i

tests\gs_test.s: tests\gs_test.c.s
.PHONY : tests\gs_test.s

# target to generate assembly for a file
tests\gs_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test.dir\tests\gs_test.c.s
.PHONY : tests\gs_test.c.s

tests\gs_test_gop_blocking.obj: tests\gs_test_gop_blocking.c.obj
.PHONY : tests\gs_test_gop_blocking.obj

# target to build an object file
tests\gs_test_gop_blocking.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_blocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_blocking.dir\tests\gs_test_gop_blocking.c.obj
.PHONY : tests\gs_test_gop_blocking.c.obj

tests\gs_test_gop_blocking.i: tests\gs_test_gop_blocking.c.i
.PHONY : tests\gs_test_gop_blocking.i

# target to preprocess a source file
tests\gs_test_gop_blocking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_blocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_blocking.dir\tests\gs_test_gop_blocking.c.i
.PHONY : tests\gs_test_gop_blocking.c.i

tests\gs_test_gop_blocking.s: tests\gs_test_gop_blocking.c.s
.PHONY : tests\gs_test_gop_blocking.s

# target to generate assembly for a file
tests\gs_test_gop_blocking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_blocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_blocking.dir\tests\gs_test_gop_blocking.c.s
.PHONY : tests\gs_test_gop_blocking.c.s

tests\gs_test_gop_nonblocking.obj: tests\gs_test_gop_nonblocking.c.obj
.PHONY : tests\gs_test_gop_nonblocking.obj

# target to build an object file
tests\gs_test_gop_nonblocking.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_nonblocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_nonblocking.dir\tests\gs_test_gop_nonblocking.c.obj
.PHONY : tests\gs_test_gop_nonblocking.c.obj

tests\gs_test_gop_nonblocking.i: tests\gs_test_gop_nonblocking.c.i
.PHONY : tests\gs_test_gop_nonblocking.i

# target to preprocess a source file
tests\gs_test_gop_nonblocking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_nonblocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_nonblocking.dir\tests\gs_test_gop_nonblocking.c.i
.PHONY : tests\gs_test_gop_nonblocking.c.i

tests\gs_test_gop_nonblocking.s: tests\gs_test_gop_nonblocking.c.s
.PHONY : tests\gs_test_gop_nonblocking.s

# target to generate assembly for a file
tests\gs_test_gop_nonblocking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_test_gop_nonblocking.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_test_gop_nonblocking.dir\tests\gs_test_gop_nonblocking.c.s
.PHONY : tests\gs_test_gop_nonblocking.c.s

tests\gs_unique_test.obj: tests\gs_unique_test.c.obj
.PHONY : tests\gs_unique_test.obj

# target to build an object file
tests\gs_unique_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_unique_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_unique_test.dir\tests\gs_unique_test.c.obj
.PHONY : tests\gs_unique_test.c.obj

tests\gs_unique_test.i: tests\gs_unique_test.c.i
.PHONY : tests\gs_unique_test.i

# target to preprocess a source file
tests\gs_unique_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_unique_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_unique_test.dir\tests\gs_unique_test.c.i
.PHONY : tests\gs_unique_test.c.i

tests\gs_unique_test.s: tests\gs_unique_test.c.s
.PHONY : tests\gs_unique_test.s

# target to generate assembly for a file
tests\gs_unique_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\gs_unique_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\gs_unique_test.dir\tests\gs_unique_test.c.s
.PHONY : tests\gs_unique_test.c.s

tests\lob_bnd_test.obj: tests\lob_bnd_test.c.obj
.PHONY : tests\lob_bnd_test.obj

# target to build an object file
tests\lob_bnd_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lob_bnd_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\lob_bnd_test.dir\tests\lob_bnd_test.c.obj
.PHONY : tests\lob_bnd_test.c.obj

tests\lob_bnd_test.i: tests\lob_bnd_test.c.i
.PHONY : tests\lob_bnd_test.i

# target to preprocess a source file
tests\lob_bnd_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lob_bnd_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\lob_bnd_test.dir\tests\lob_bnd_test.c.i
.PHONY : tests\lob_bnd_test.c.i

tests\lob_bnd_test.s: tests\lob_bnd_test.c.s
.PHONY : tests\lob_bnd_test.s

# target to generate assembly for a file
tests\lob_bnd_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\lob_bnd_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\lob_bnd_test.dir\tests\lob_bnd_test.c.s
.PHONY : tests\lob_bnd_test.c.s

tests\obbox_test.obj: tests\obbox_test.c.obj
.PHONY : tests\obbox_test.obj

# target to build an object file
tests\obbox_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\obbox_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\obbox_test.dir\tests\obbox_test.c.obj
.PHONY : tests\obbox_test.c.obj

tests\obbox_test.i: tests\obbox_test.c.i
.PHONY : tests\obbox_test.i

# target to preprocess a source file
tests\obbox_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\obbox_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\obbox_test.dir\tests\obbox_test.c.i
.PHONY : tests\obbox_test.c.i

tests\obbox_test.s: tests\obbox_test.c.s
.PHONY : tests\obbox_test.s

# target to generate assembly for a file
tests\obbox_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\obbox_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\obbox_test.dir\tests\obbox_test.c.s
.PHONY : tests\obbox_test.c.s

tests\poly_test.obj: tests\poly_test.c.obj
.PHONY : tests\poly_test.obj

# target to build an object file
tests\poly_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\poly_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\poly_test.dir\tests\poly_test.c.obj
.PHONY : tests\poly_test.c.obj

tests\poly_test.i: tests\poly_test.c.i
.PHONY : tests\poly_test.i

# target to preprocess a source file
tests\poly_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\poly_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\poly_test.dir\tests\poly_test.c.i
.PHONY : tests\poly_test.c.i

tests\poly_test.s: tests\poly_test.c.s
.PHONY : tests\poly_test.s

# target to generate assembly for a file
tests\poly_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\poly_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\poly_test.dir\tests\poly_test.c.s
.PHONY : tests\poly_test.c.s

tests\sarray_sort_test.obj: tests\sarray_sort_test.c.obj
.PHONY : tests\sarray_sort_test.obj

# target to build an object file
tests\sarray_sort_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_sort_test.dir\tests\sarray_sort_test.c.obj
.PHONY : tests\sarray_sort_test.c.obj

tests\sarray_sort_test.i: tests\sarray_sort_test.c.i
.PHONY : tests\sarray_sort_test.i

# target to preprocess a source file
tests\sarray_sort_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_sort_test.dir\tests\sarray_sort_test.c.i
.PHONY : tests\sarray_sort_test.c.i

tests\sarray_sort_test.s: tests\sarray_sort_test.c.s
.PHONY : tests\sarray_sort_test.s

# target to generate assembly for a file
tests\sarray_sort_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_sort_test.dir\tests\sarray_sort_test.c.s
.PHONY : tests\sarray_sort_test.c.s

tests\sarray_transfer_test.obj: tests\sarray_transfer_test.c.obj
.PHONY : tests\sarray_transfer_test.obj

# target to build an object file
tests\sarray_transfer_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_transfer_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_transfer_test.dir\tests\sarray_transfer_test.c.obj
.PHONY : tests\sarray_transfer_test.c.obj

tests\sarray_transfer_test.i: tests\sarray_transfer_test.c.i
.PHONY : tests\sarray_transfer_test.i

# target to preprocess a source file
tests\sarray_transfer_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_transfer_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_transfer_test.dir\tests\sarray_transfer_test.c.i
.PHONY : tests\sarray_transfer_test.c.i

tests\sarray_transfer_test.s: tests\sarray_transfer_test.c.s
.PHONY : tests\sarray_transfer_test.s

# target to generate assembly for a file
tests\sarray_transfer_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sarray_transfer_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sarray_transfer_test.dir\tests\sarray_transfer_test.c.s
.PHONY : tests\sarray_transfer_test.c.s

tests\sort_test.obj: tests\sort_test.c.obj
.PHONY : tests\sort_test.obj

# target to build an object file
tests\sort_test.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test.dir\tests\sort_test.c.obj
.PHONY : tests\sort_test.c.obj

tests\sort_test.i: tests\sort_test.c.i
.PHONY : tests\sort_test.i

# target to preprocess a source file
tests\sort_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test.dir\tests\sort_test.c.i
.PHONY : tests\sort_test.c.i

tests\sort_test.s: tests\sort_test.c.s
.PHONY : tests\sort_test.s

# target to generate assembly for a file
tests\sort_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test.dir\tests\sort_test.c.s
.PHONY : tests\sort_test.c.s

tests\sort_test2.obj: tests\sort_test2.c.obj
.PHONY : tests\sort_test2.obj

# target to build an object file
tests\sort_test2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test2.dir\tests\sort_test2.c.obj
.PHONY : tests\sort_test2.c.obj

tests\sort_test2.i: tests\sort_test2.c.i
.PHONY : tests\sort_test2.i

# target to preprocess a source file
tests\sort_test2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test2.dir\tests\sort_test2.c.i
.PHONY : tests\sort_test2.c.i

tests\sort_test2.s: tests\sort_test2.c.s
.PHONY : tests\sort_test2.s

# target to generate assembly for a file
tests\sort_test2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\sort_test2.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\sort_test2.dir\tests\sort_test2.c.s
.PHONY : tests\sort_test2.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... comm_test
	@echo ... crystal_test
	@echo ... findpts_el_2_test
	@echo ... findpts_el_2_test2
	@echo ... findpts_el_3_test
	@echo ... findpts_el_3_test2
	@echo ... findpts_local_test
	@echo ... findpts_test
	@echo ... findpts_test_ms
	@echo ... gs
	@echo ... gs_test
	@echo ... gs_test_gop_blocking
	@echo ... gs_test_gop_nonblocking
	@echo ... gs_unique_test
	@echo ... lob_bnd_test
	@echo ... obbox_test
	@echo ... poly_test
	@echo ... sarray_sort_test
	@echo ... sarray_transfer_test
	@echo ... sort_test
	@echo ... sort_test2
	@echo ... src/comm.obj
	@echo ... src/comm.i
	@echo ... src/comm.s
	@echo ... src/crystal.obj
	@echo ... src/crystal.i
	@echo ... src/crystal.s
	@echo ... src/fail.obj
	@echo ... src/fail.i
	@echo ... src/fail.s
	@echo ... src/fcrystal.obj
	@echo ... src/fcrystal.i
	@echo ... src/fcrystal.s
	@echo ... src/findpts.obj
	@echo ... src/findpts.i
	@echo ... src/findpts.s
	@echo ... src/findpts_el_2.obj
	@echo ... src/findpts_el_2.i
	@echo ... src/findpts_el_2.s
	@echo ... src/findpts_el_3.obj
	@echo ... src/findpts_el_3.i
	@echo ... src/findpts_el_3.s
	@echo ... src/findpts_local.obj
	@echo ... src/findpts_local.i
	@echo ... src/findpts_local.s
	@echo ... src/gs.obj
	@echo ... src/gs.i
	@echo ... src/gs.s
	@echo ... src/gs_local.obj
	@echo ... src/gs_local.i
	@echo ... src/gs_local.s
	@echo ... src/lob_bnd.obj
	@echo ... src/lob_bnd.i
	@echo ... src/lob_bnd.s
	@echo ... src/obbox.obj
	@echo ... src/obbox.i
	@echo ... src/obbox.s
	@echo ... src/poly.obj
	@echo ... src/poly.i
	@echo ... src/poly.s
	@echo ... src/sarray_sort.obj
	@echo ... src/sarray_sort.i
	@echo ... src/sarray_sort.s
	@echo ... src/sarray_transfer.obj
	@echo ... src/sarray_transfer.i
	@echo ... src/sarray_transfer.s
	@echo ... src/sort.obj
	@echo ... src/sort.i
	@echo ... src/sort.s
	@echo ... src/tensor.obj
	@echo ... src/tensor.i
	@echo ... src/tensor.s
	@echo ... tests/comm_test.obj
	@echo ... tests/comm_test.i
	@echo ... tests/comm_test.s
	@echo ... tests/crystal_test.obj
	@echo ... tests/crystal_test.i
	@echo ... tests/crystal_test.s
	@echo ... tests/findpts_el_2_test.obj
	@echo ... tests/findpts_el_2_test.i
	@echo ... tests/findpts_el_2_test.s
	@echo ... tests/findpts_el_2_test2.obj
	@echo ... tests/findpts_el_2_test2.i
	@echo ... tests/findpts_el_2_test2.s
	@echo ... tests/findpts_el_3_test.obj
	@echo ... tests/findpts_el_3_test.i
	@echo ... tests/findpts_el_3_test.s
	@echo ... tests/findpts_el_3_test2.obj
	@echo ... tests/findpts_el_3_test2.i
	@echo ... tests/findpts_el_3_test2.s
	@echo ... tests/findpts_local_test.obj
	@echo ... tests/findpts_local_test.i
	@echo ... tests/findpts_local_test.s
	@echo ... tests/findpts_test.obj
	@echo ... tests/findpts_test.i
	@echo ... tests/findpts_test.s
	@echo ... tests/findpts_test_ms.obj
	@echo ... tests/findpts_test_ms.i
	@echo ... tests/findpts_test_ms.s
	@echo ... tests/gs_test.obj
	@echo ... tests/gs_test.i
	@echo ... tests/gs_test.s
	@echo ... tests/gs_test_gop_blocking.obj
	@echo ... tests/gs_test_gop_blocking.i
	@echo ... tests/gs_test_gop_blocking.s
	@echo ... tests/gs_test_gop_nonblocking.obj
	@echo ... tests/gs_test_gop_nonblocking.i
	@echo ... tests/gs_test_gop_nonblocking.s
	@echo ... tests/gs_unique_test.obj
	@echo ... tests/gs_unique_test.i
	@echo ... tests/gs_unique_test.s
	@echo ... tests/lob_bnd_test.obj
	@echo ... tests/lob_bnd_test.i
	@echo ... tests/lob_bnd_test.s
	@echo ... tests/obbox_test.obj
	@echo ... tests/obbox_test.i
	@echo ... tests/obbox_test.s
	@echo ... tests/poly_test.obj
	@echo ... tests/poly_test.i
	@echo ... tests/poly_test.s
	@echo ... tests/sarray_sort_test.obj
	@echo ... tests/sarray_sort_test.i
	@echo ... tests/sarray_sort_test.s
	@echo ... tests/sarray_transfer_test.obj
	@echo ... tests/sarray_transfer_test.i
	@echo ... tests/sarray_transfer_test.s
	@echo ... tests/sort_test.obj
	@echo ... tests/sort_test.i
	@echo ... tests/sort_test.s
	@echo ... tests/sort_test2.obj
	@echo ... tests/sort_test2.i
	@echo ... tests/sort_test2.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

